Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true

# 01 Database Server
    config.vm.define "db01" do |mariadb|
        mariadb.vm.box = "centos/stream9"
        mariadb.vm.hostname = "db01"
        mariadb.vm.network "private_network", ip: "192.168.56.15"
        mariadb.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.name = "mariadb_Server"
        end
    end 
# 02 Memcach Server
    config.vm.define "mc01" do |memcach|
        memcach.vm.box = "centos/stream9"
        memcach.vm.hostname = "mc01"
        memcach.vm.network "private_network", ip: "192.168.56.14"
        memcach.vm.provider "virtualbox" do |vb|
            vb.memory = 900
            vb.name = "memcach_Server"
        end
    end
# 03 RabbitMQ Server
    config.vm.define "rmq01" do |rmq01|
        rmq01.vm.box = "centos/stream9"
        rmq01.vm.hostname = "rmq01"
        rmq01.vm.network "private_network", ip: "192.168.56.13"
        rmq01.vm.provider "virtualbox" do |vb|
            vb.memory = 600
            vb.name = "RabbitMQ_Server"
        end
    end
# 04 Application Server
    config.vm.define "app01" do |app01|
        app01.vm.box = "centos/stream9"
        app01.vm.hostname = "app01"
        app01.vm.network "private_network", ip: "192.168.56.12"
        app01.vm.provider "virtualbox" do |vb|
            vb.memory = 4200
            vb.name = "Tomcat_Server"
        end
    end
# 05 web Server
    config.vm.define "web01" do |web01|
        web01.vm.box = "ubuntu/jammy64"
        web01.vm.hostname = "web01"
        web01.vm.network "private_network", ip: "192.168.56.11" 
        web01.vm.provider "virtualbox" do |vb|
            vb.memory = 800
            vb.name = "Nginx_Server"
        end
    end
end
